### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by Chromer163** [DanBigioi/DiffusionVideoEditing#1]
Thanks for your awesome and creative work!
I read your paper and try to reproduction the performance. but via diffusion method, it will be convenient and helpful if you could provide the pretrained model, Thanks.

**Comment by DanBigioi** [comment]
Hi! 

Thanks for your interest in the project! I will provide the pretrained models + updated code in approx. 4-6 weeks, as well as an improved version of the paper and method, as I await reviews for the work.

**Comment by DanBigioi** [comment]
Hi @Chromer163 The pretrained models and code to run them are now available
