### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by Li-Jicheng** [DanBigioi/DiffusionVideoEditing#9]
Hi Dan,  hope everything is going well :)

I couldn't find implementations for some of the evaluation metrics. Specifically, LSE-C, LSE-D, SSIM, PSNR, CPBD.

Could you please guide where I can locate these scripts from the projects, or which GitHub repo I should visit to borrow these codes?

Thanks for your time and patience :)

Li

**Comment by DanBigioi** [comment]
Hi Jicheng, 

One of my coathors actually ran the evaluations, so I'll ask him to send them to me for SSIM, PSNR, and CPBD but in theory they aren't too difficult to implement. For LSE-C and LSE-D we used this repo: https://github.com/Rudrabha/Wav2Lip/tree/master/evaluation. 

Best, 
Dan

**Comment by Li-Jicheng** [comment]
Thanks for your quick response Dan! Yeah I agree with that it's quite straightforward to implement, just trying to make sure I did not miss any part of the code and trying to be lazy lol.  Thanks for the feedback, I can try to fix it quickly by myself for now. Thanks for your help as always:)

**Comment by DanBigioi** [comment]
No problem, and good luck!
